apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: glpi

resources:
  - 00-namespace-glpi.yaml
  - 01-pvc-content-glpi.yaml
  - 02-glpi-deploy.yaml
  - 03-glpi-svc.yaml
  - 04-glpi-ingress.yaml
