replicaCount: 1

image:
  tag: latest

ingress:
  enabled: true
  host: glpi.dev.local

persistence:
  storageClass: nfs-static
  size: 4Gi

glpi:
  dbHost: "10.20.71.10:3306"
  dbName: "glpi_dev"
  dbUser: "glpi_user"
  dbPassword: ""
